### ISSUE TITLE
Missing dependencies in install section

### ISSUE THREAD

**Issue by laolux** [scrapy/scrapy.org#107]
There are (at least) 2 more Python packages needed for scrapy which are not listed in the install section:
PyDispatcher >= 2.0.5 http://pydispatcher.sourceforge.net
service-identity https://service-identity.readthedocs.io

Would be great to see those added.

**Comment by redapple** [comment]
Hey @laolux ,
which section are you referring to? is it https://docs.scrapy.org/en/latest/intro/install.html?
It mentions only some of the dependencies.
> Scrapy is written in pure Python and depends on a few key Python packages (**among others**):

It is assumed that users with install scrapy via `pip` or `conda`, where dependent packages will be fetched and installed too when installing scrapy.
Are you having issues installing scrapy?

**Comment by laolux** [comment]
Yes, that's the section I was referring to. I noticed the "(among others)", but think it would not hurt to add the 2 I mentioned. It might help others.

scrapy installed well with pip 👍, but I am looking at packaging it for Fedora and thus also tried (and finally succeded) installing from source.
