### ISSUE TITLE
Link points to wrong resource in  resources/videos

### ISSUE THREAD

**Issue by VineethKanaparthi** [scrapy/scrapy.org#126]
In videos section.

Scrapy Workshop by Karthik Ananth points to 
```https://www.youtube.com/watch?v=eD8XVXLlUTE```
instead of
```https://www.youtube.com/watch?v=0VssOTV5eoc```

**Comment by VineethKanaparthi** [comment]
I've created a pull request, regarding the same.

**Comment by pablohoffman** [comment]
pull request merged, thanks!
