### ISSUE TITLE
A few people don't see headers

### ISSUE THREAD

**Issue by serhii73** [scrapy/scrapy.org#143]
Hello everyone.
I use Fedora and Firefox and I don't see headers on https://scrapy.org/
Also, I asked a few people and they tell me they also can't see headers.
One use Firefox and Linux Mint.
The second guy uses Manjaro and Firefox.
![Screenshot_2019-06-08 Scrapy A Fast and Powerful Scraping and Web Crawling Framework](https://user-images.githubusercontent.com/24910277/59151530-62fe9380-8a3d-11e9-9de3-a8014668148a.png)
On Chromium all good
![Screenshot from 2019-06-08 22-16-45](https://user-images.githubusercontent.com/24910277/59151536-6eea5580-8a3d-11e9-96aa-50f5efc43c27.png)
My Firefox is 67.0 (64-bit)
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by serhii73** [comment]
It is Firefox from different Linux distributives.
![m](https://user-images.githubusercontent.com/24910277/59151642-35b2e500-8a3f-11e9-9350-e3da447e0ae9.png)
![1](https://user-images.githubusercontent.com/24910277/59151643-35b2e500-8a3f-11e9-9ca3-9e0bb0c9cfe7.png)
But Firefox from windows works.
![w](https://user-images.githubusercontent.com/24910277/59151651-5a0ec180-8a3f-11e9-86fb-e81cac0b9afa.png)

**Comment by serhii73** [comment]
@dangra

**Comment by noviluni** [comment]
I can confirm what @serhii73 said and I added a PR to fix it.
