### ISSUE TITLE
Documentation URL doesn't work on Index

### ISSUE THREAD

**Issue by realslimshanky** [scrapy/scrapy.org#202]
On https://scrapy.org/ top navigation bar, `Documentation` is pointing to `https://scrapy.org/https://docs.scrapy.org/` instead of `https://scrapy.org/https://docs.scrapy.org/`

https://github.com/scrapy/scrapy.org/commit/b63ddd7e493dbd1e8d56c0e39875616b7bc813b8 this commit is the source of the issue and can be resolve by fixing this part of the repo code https://github.com/scrapy/scrapy.org/blob/master/_includes/header.html#L13-L24

**Comment by Gallaecio** [comment]
Fixed by https://github.com/scrapy/scrapy.org/pull/203
