### ISSUE TITLE
Site still says 2.5.0

### ISSUE THREAD

**Issue by danger89** [scrapy/scrapy.org#212]
The [website](https://scrapy.org/) still says version 2.5.0 is the latest. But I think the website should be rolled-out with 2.5.1.

**Comment by Gallaecio** [comment]
You might have a cached version of the website, it says 2.5.1 on my end.
![Screenshot_20211223_001206](https://user-images.githubusercontent.com/705211/147165226-0ad8c165-ef09-422d-aaf6-81b3f9185ae4.png)
