### ISSUE TITLE
Can't download latest version (ZIP)

### ISSUE THREAD

**Issue by spottuit** [scrapy/scrapy.org#49]
When I visited [the scrapy download page](http://scrapy.org/download/) I was trying to get the zip file from the latest version:
![image](https://cloud.githubusercontent.com/assets/9430751/11421620/34602d96-9436-11e5-84bf-74e0beadf29b.png)

and I got a download error:
![image](https://cloud.githubusercontent.com/assets/9430751/11421657/6f927252-9436-11e5-9ca6-fae82632291c.png)

Link I got send to when clicking button: https://codeload.github.com/scrapy/scrapy/legacy.zip/latest

**EDIT:**

I can't download the tarball too:
![image](https://cloud.githubusercontent.com/assets/9430751/11421888/c0f3f160-9437-11e5-8732-1f3121497af6.png)

Link I got send to when clicking button: https://codeload.github.com/scrapy/scrapy/legacy.tar.gz/latest

**Comment by pablohoffman** [comment]
Thanks for reporting!. We're taking a look.
