### ISSUE TITLE
Handling of outdated company information

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy.org#57]
What's the policy about outdated information on the scrapy.org site?

I noticed that several of the companies/projects are no longer existing.
Should those be removed or at least de-linked (moved to a 'historically used scrapy' subsection)?

**Comment by pablohoffman** [comment]
good idea @nyov

**Comment by nyov** [comment]
A list of the broken links I found
```
http://www.my.jobs/ (redirect domain)
http://www.bitehunter.com/ (dead domain)
http://www.innerballoons.com/ (resolving but no webserver)
http://www.coenterprise.com/solutions/applications/bookradar (404, no follow up found)
http://www.cavucador.com.br/ (dead domain)
```

@pablohoffman, I would create a quick PR, but which change (removing/cleaning entries or adding a historical section) should it be?

**Comment by nyov** [comment]
I see `my.jobs` has just reappeared for me.

@rvnovaes, are you aware what happened to http://www.cavucador.com.br/ ? Is the site gone permanently?

**Comment by redapple** [comment]
@nyov ,

- `my.jobs` by DirectEmployers also works for me
- BiteHunter looks dead indeed
- innerballoons [was acquired by Yext.com](http://www.yext.com/blog/2014/12/yext-acquires-innerballoons/) 

I think it's fine to remove the old entries, without historical section

**Comment by nyov** [comment]
Alright.

I've assumed cavucador is gone permanently as well, since there was no reply from the original committer.

**Comment by redapple** [comment]
Thanks @nyov !
