### ISSUE TITLE
On the /support/ part of the site: Data Quarry link is dead

### ISSUE THREAD

**Issue by nocomplexity** [scrapy/scrapy.org#72]
On the http://scrapy.org/support/  part of the Scrapy site the link to the Data Quarry organization is dead. 

Suggestion:Remove temporary this organization until fixed?
![screenshot from 2016-07-26 17-28-42](https://cloud.githubusercontent.com/assets/12949360/17144334/af34396a-5356-11e6-9907-5a00761517f0.png)

**Comment by redapple** [comment]
Thanks for reporting @nocomplexity , I'll fix this shortly.
