### ISSUE TITLE
Add Anaconda/Conda-Forge badges

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy.org#95]
We can show conda-forge badges on the homepage.
See https://anaconda.org/conda-forge/scrapy/badges

**Comment by soumallyadev07** [comment]
Hey! Even though this issue is really old, is it still active and can be worked upon?

**Comment by Gallaecio** [comment]
I think so, yes.

**Comment by sameer1604** [comment]
Hey! Which tags exactly need to be added here?

**Comment by Gallaecio** [comment]
I believe https://anaconda.org/conda-forge/scrapy/badges/version.svg should be enough, similar to what we have for PyPI.

**Comment by Gallaecio** [comment]
Fixed by #213
